sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: HGLEtV5ABwtQkqKJMEZQKRut8C0dFfY7z1zrj+7qqBz29dND2hPz/NKhBhKWUuUcxCQft+YOkX6QvI+cFFiqpQ8/d24zVC0t6fN+1leCXSbQXhf0kjIHXU+GekcQDdng93o3/SXCEZuQuleGipaALgqhgpNiphZVKDoKNUEpi4gPj/E11C9AjisVGAcTCm4+rd/4mvzS2DL1yFcUv5bMxjttAfIJIZEbAsK6kjB+9KegUumms5p87CXLSwk0ET0VIQs0tkzYHN599Ewn6vE0jV7s7guPEvopeMn2olLZOK5mbxEiYfdtBqqDrP11KNiS0vKEcDeE2ofumJ5dW7BWjtMvSSMu6FSn2CCzm5qqqwfO9t3ruK64sAuBMAtVofUkftGG6GoSYUX45mzXnfDnMg5acg9TS+TJulBXylLhnQ+5VFo72Rz4twcKq3mxCA63zQI1lVnZYZW0RZCL2n7EpzsjzL3pOWy6Jlak0lQ35zL5iOnl2YmkVR7g1TB9JSGlRS2Tss/XSXRUsctD0WE+n22HrRrD6WiMIYcb4WFlOhrjvHGnhqtY9J2WLdZqE7lrWCua3XezG95CDTqX0HKS9P1VEBLjuEiPHbGrlCywznTBEoXruZpuit5xpdjhPO3m403JlqpKBiQEpenhWEcmXpjymrQkfVKqLHVU21GHyhA=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: NcofFdmf7oYlXubBYxjlLDWPaV34em6E+bkTiKZdS/Cuu0cJRS0dQPxW2zR1oXl9arRWNCdhuhriWtpTd0atguOJfFLQC5zkw8jYU8se7og3VK92m/uVbKTHq0g/nIV9ionEIAPuNpnF6MtyU99g/DrClZnWJBbmz9OR1GbMyn84VzaZQTpXzTTDs9Y55xp74hC/PYTvNQlwas7auNd4aJy07cW4vLZXSrTjZwkPmuBXJ/p7LXqkjkrmtD4HxV68mvW3iAmMfi+XlQseHK8mQfag7KSnGnu8HE7ezoeBwr/de4LMjh+Cjdq54Mt8dGhkwTeVO9SSzcWxaYNaH0iegmUqPLtlhIeDiUrqR1epjFJmELcA3gjQNDG2wPunTvXdBG010b+zfqgVFEHv1LHj6UvltFymJdM9MmQCkIkMf6XjFK0+6ib3yA2VAUCoF6sitGMVUK6p0u7gTAYIzUAToJG5Fy5u86qKa3Oaa59BxPndI6kODuwjfeJMRpDLJavOFIEmurDO2uRwxUzYvy9UkLq/8pENqZ/+x/BD3zH9QD6mONvB8tkQj7zp4dIGU9N0RxnCfjrftqztroJ0jRnGzKfT/ggjkBtooIwoFxxqFnH2ywbKfMZSx0UmYxLGbCGf+LRxQKApWKcOEOVQK2iKXHiwaR0vLcXw0AqnEoYXHeE=
